import: comunica/travis-presets:yarn-monorepo.yml@master
script:
  - lerna run integration --concurrency 1
deploy:
  - provider: script
    skip-cleanup: true
    script: ./.travis/deploy_browser.sh
    on:
      tags: false
      branch: master
      condition: $NODE_MAIN = true
      os: "linux"
  - provider: script
    skip-cleanup: true
    script: ./.travis/deploy_browser.sh
    on:
      tags: true
      all_branches: true
      condition: $NODE_MAIN = true
      os: "linux"
